---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

install:
  - curl -qLo terraform-docs https://github.com/segmentio/terraform-docs/releases/download/v0.6.0/terraform-docs-v0.6.0-linux-amd64
  - chmod +x terraform-docs
  - PATH=$(pwd):$PATH
  - pip install cookiecutter tf-readme-validator
  - pip install pep8
  - pip install pycodestyle
  - pip install pylint
  - terraform-docs --version
  - cookiecutter --version
  - tf_readme_validator.py --version

script:
  - cookiecutter --no-input .
  - cd tf-module-default_module
  - tf_readme_validator.py
  - pep8 ../hooks/
  - pycodestyle ../hooks/
  - pylint -f colorized -rn ../hooks/
